language: cpp
compiler:
  - gcc
os:
  - linux
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y cmake
 - sudo wget https://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0.tgz
 - sudo tar xf glew-2.1.0.tgz
 - cd glew-2.1.0
 - sudo make
 - sudo make install
 - cd ..
 - pip install --user cpp-coveralls
script: 
  - cmake -DCOVERAGE=1 . && make && make unittest
  - ./test/unittest
after_success:
  - coveralls --root . -e test -E ".*gtest.*" -E ".*CMakeFiles.*" -E ".*colors.*\.hpp"