language: cpp
compiler:
  - gcc
os:
  - linux
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev dos2unix cmake
 - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - sudo tar xf release-1.8.0.tar.gz
 - cd googletest-release-1.8.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo make install
 - cd ..
 - sudo wget https://downloads.sourceforge.net/project/glew/glew/2.1.0/glew-2.1.0.tgz
 - sudo tar xf glew-2.1.0.tgz
 - cd glew-2.1.0
 - make
 - sudo make install
 - cd ..
script: cmake . && make && make unittest